splitBraceに渡すテキストが不適切に分割される問題の修正
OUCC/KoeBook pull request #21
Opened 2024-03-15 14:50 UTC by TakenPt

2024-03-15 15:45 UTC, aiueo-1234 commented
Closes #13

2024-03-16 14:00 UTC, miyaji255 requested changes

2024-03-16 14:00 UTC, miyaji255 commented on Epub/KoeBook.Epub/Contracts/Services/ISplitBraceService.cs
> +    List<string> GetText();
`List<string>`ではなく`IEnumerable<string>`に変更するのはどうでしょうか？

2024-03-16 14:00 UTC, miyaji255 commented on Epub/KoeBook.Epub/Services/SplitBraceService.cs
> +    private List<StringBuilder> stringBuilders = new();
別のプロセスから同時にアクセスしたときに正しく動作するか確認してください。

2024-03-19 04:35 UTC, miyaji255 commented on Epub/KoeBook.Epub/Services/ScrapingAozoraService.cs
>                                      if (document.Chapters[chapterNum].Sections[sectionNum].Elements[^1] is Paragraph paragraph1)
こうすればfor文を使わずにかけませんか？for文は見通しが悪くなるのでできるだけ使わないほうが良いです。
```cs
var forcusSectionElements = document.Chapters[chapterNum].Sections[sectionNum].Elements;
if (forcusSectionElements[^1] is Paragraph paragraph)
{
    var splitted = _splitBraceService.SplitBrace(TextProcess(element));
    var first = true;

    foreach (var text in splitted)
    {
        if (first)
        {
            paragraph.Text += text;
            first = false;
        }
        else
            forcusSectionElements.Add(new Paragraph() { Text = text });
    }
}
```

2024-03-19 04:42 UTC, miyaji255 commented on KoeBook.Core/Utility/StringStorer.cs
> +        }
`List<StringBuilder>`は必要ありませんでしたか？これなら素の`StringBuilder`を使えばよいと思います。

2024-03-19 06:46 UTC, TakenPt commented on Epub/KoeBook.Epub/Services/ScrapingAozoraService.cs
>                                      if (document.Chapters[chapterNum].Sections[sectionNum].Elements[^1] is Paragraph paragraph1)
それに変更します

2024-03-19 06:52 UTC, TakenPt commented on KoeBook.Core/Utility/StringStorer.cs
> +        }
これを書いた時はListでなくても良いと思っていましたが、今、青空文庫の書式を見て、考えると、Storeの部分にstringだけでなく、List<string>も受け付けてくれないときついので、List<StringBuilder>に変更します。

2024-03-20 07:50 UTC, miyaji255 commented on KoeBook.Core/Utility/StringStorer.cs
> +        }
ListではなくIEnumerable<T>を受けてください。また、このクラスはBuilderなのでそれにあった名前にしてください。

2024-03-20 07:51 UTC, miyaji255 commented on Epub/KoeBook.Epub/Services/ScrapingAozoraService.cs
>                                      if (document.Chapters[chapterNum].Sections[sectionNum].Elements[^1] is Paragraph paragraph1)
これを入れると書きやすくなりますか？
```cs
/// <summary>
/// 
/// </summary>
/// <typeparam name="TSource"><paramref name="source"/>の要素の型</typeparam>
/// <returns>first: 指定されたシーケンスの最初の要素, rest: 残りの要素, 複数回のイテレートは保証しません</returns>
/// <exception cref="ArgumentNullException"><paramref name="source"/>がnullです</exception>
/// <exception cref="InvalidOperationException">ソース シーケンスが空です</exception>
public static (TSource first, IEnumerable<TSource> rest) FirstWithRest<TSource>(this IEnumerable<TSource> source)
{
    ArgumentNullException.ThrowIfNull(source);

    var enumerator = source.GetEnumerator();

    if (!enumerator.MoveNext())
        throw new InvalidOperationException("ソース シーケンスが空です");

    return (enumerator.Current, GetRest(enumerator));

    static IEnumerable<T> GetRest<T>(IEnumerator<T> enumerator)
    {
        using (enumerator)
        {
            while (enumerator.MoveNext())
                yield return enumerator.Current;
        }
    }
}
```

2024-03-23 13:13 UTC, miyaji255 requested changes

2024-03-23 13:13 UTC, miyaji255 commented on Epub/KoeBook.Epub/Services/SplitBraceService.cs
> +    public IEnumerable<string> SplitBrace(IEnumerable<string> texts)
テストを追加してください

2024-03-23 13:13 UTC, miyaji255 commented on KoeBook.Core/Utility/StringStoreBuilder.cs
> +    public class StringStoreBuilder
テストを追加してください。また名前がStoreのBuilderになっています。`SplittedLineBuilder`にしておいてください。また、Store, ReleaseをAppend, ToLinesAndClearにしてください

2024-03-23 13:13 UTC, miyaji255 commented on KoeBook.Core/Utility/EnumerableEx.cs
> +        /// </summary>
空summaryはやめてください。また、これを使うならテストを書いてください。

2024-03-23 13:13 UTC, miyaji255 commented on KoeBook.Core/Utility/StringStoreBuilder.cs
> +            foreach (var (value, isLast) in rest.WithLastFlag())
FirstとLastの両方が必要なら私が渡したコードを参考に`(value, isFirst, isLast)をとれる拡張を用意してください。また、`Length = 0`ではなく`Clear`のほうが明瞭です。

2024-03-23 13:14 UTC, miyaji255 commented on Epub/KoeBook.Epub/Services/ScrapingAozoraService.cs
>                                      if (document.Chapters[chapterNum].Sections[sectionNum].Elements[^1] is Paragraph paragraph1)
199行目のループも変更できませんか？

2024-03-30 06:27 UTC, miyaji255 commented on Epub/KoeBook.Epub/Services/ScrapingAozoraService.cs
> +                        var first = true;
ここは元あったものに合わせて修正したのですが、被ってないですか？

2024-03-30 16:56 UTC, TakenPt commented on Epub/KoeBook.Epub/Services/ScrapingAozoraService.cs
> +                        var first = true;
425行目がいりません。
消すのをわすれてます。

2024-03-30 23:29 UTC, miyaji255 approved these changes

2024-03-30 23:32 UTC, merged