なろうServiceのリファクタリング
OUCC/KoeBook pull request #24
Opened 2024-03-16 08:40 UTC by miyaji255

2024-03-31 08:32 UTC, aiueo-1234 requested changes
あとどこかのタイミングでMainViewModel.csの157行目を"https://ncode.syosetu.com"に変更しておいてほしいです

2024-03-31 08:32 UTC, aiueo-1234 commented on Epub/KoeBook.Epub/Services/ScrapingNaroService.cs
>              // auther の取得
auther->author

2024-03-31 08:32 UTC, aiueo-1234 commented on Epub/KoeBook.Epub/Services/ScrapingNaroService.cs
>          private readonly IHttpClientFactory _httpCliantFactory = httpClientFactory;
Cliant -> Client

2024-03-31 08:32 UTC, aiueo-1234 commented on Epub/KoeBook.Epub/Services/ScrapingNaroService.cs
> +                                await _scrapingClientService.GetAsStreamAsync(img.Source, fileSr, ct).ConfigureAwait(false);
fileSrはFlush不要ですか？必要な気がします。

2024-03-31 08:32 UTC, aiueo-1234 commented on Epub/KoeBook.Epub/Services/ScrapingNaroService.cs
> +                var html = await _scrapingClientService.GetAsStringAsync($"{BaseUrl}/{ncode}", ct).ConfigureAwait(false);
ユーザーエージェントを設定してください

2024-03-31 09:43 UTC, miyaji255 commented on Epub/KoeBook.Epub/Services/ScrapingNaroService.cs
> +                var html = await _scrapingClientService.GetAsStringAsync($"{BaseUrl}/{ncode}", ct).ConfigureAwait(false);
apiにはUAが必要ですがスクレイピングにいりません。

2024-03-31 13:33 UTC, aiueo-1234 commented on Epub/KoeBook.Epub/Services/ScrapingNaroService.cs
> +                var html = await _scrapingClientService.GetAsStringAsync($"{BaseUrl}/{ncode}", ct).ConfigureAwait(false);
実際に動かしてみたときにユーザーエージェントが不正というエラーがなろう側から送られているのでどこかで必要になってます。
タイトルを取るときには出ることがわかってるので調べてもらえますか？

2024-03-31 15:56 UTC, TakenPt requested changes
`document.Chapters.Add()` を行う時には、 `chapterTitle`の更新が必要です。
`ReadPageAsync()` 内で、`chapterTitle` を取得する際の連載の場合と短編の場合との処理が逆です。

2024-03-31 15:56 UTC, TakenPt commented on Epub/KoeBook.Epub/Services/ScrapingNaroService.cs
> +                            document.Chapters.Add(new Chapter() { Title = title });
```suggestion
                        {
                            document.Chapters.Add(new Chapter() { Title = title });
                            chapterTitle = title;
                        }
```
Chapterを追加する前か後に、chapterTitleを更新する必要があります。

2024-03-31 15:56 UTC, TakenPt commented on Epub/KoeBook.Epub/Services/ScrapingNaroService.cs
> +                : doc.QuerySelector(".chapter_title")?.InnerHtml;
連載のとき、`chapterTitle = doc.QuerySelector(".chapter_title")?.InnerHtml` で、
連載でないとき、`chapterTitle = null` です。

2024-04-01 00:05 UTC, miyaji255 commented on Epub/KoeBook.Epub/Services/ScrapingNaroService.cs
> +                var html = await _scrapingClientService.GetAsStringAsync($"{BaseUrl}/{ncode}", ct).ConfigureAwait(false);
画像の取得ででていたみたいです。

2024-04-01 04:04 UTC, aiueo-1234 approved these changes, later dismissed
LGTM

2024-04-02 09:51 UTC, aiueo-1234 approved these changes

2024-04-02 14:05 UTC, TakenPt approved these changes

2024-04-02 14:05 UTC, merged