Claudeでの解析
OUCC/KoeBook pull request #26
Opened 2024-03-22 10:06 UTC by aiueo-1234

Closes #25

2024-04-04 11:02 UTC, miyaji255 commented on Epub/KoeBook.Epub/Services/AnalyzerService.cs
> +        var _rubyReplacements = new Dictionary<string, string>();
そもそもこれって使ってますか？

2024-04-04 11:03 UTC, miyaji255 commented on Epub/KoeBook.Epub/Services/AnalyzerService.cs
>                      {
SelectMany+OfType+Select+ToArrayでLinqのみにできると思います

2024-04-23 05:10 UTC, miyaji255 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +        }
```suggestion
        catch (OperationCanceledException) { throw; }
```

2024-04-23 05:22 UTC, miyaji255 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +        return characterVoiceMapping;
```suggestion
        return response.Split("\n")
           .SkipWhile(l => !l.StartsWith("[Assign Voices]"))
           .Where(l => l.StartsWith('c'))
           .Select(l =>
           {
               var characterId = l[1..l.IndexOf('.')];
               var voiceType = l[(l.IndexOf(':') + 2)..];
               // voiceTypeが_soundGenerationSelectorService.Modelsに含まれているかチェック
               return _soundGenerationSelectorService.Models.Any(x => x.Name == voiceType)
                   ? (characterId, voiceType)
                   : (characterId, string.Empty);
           }).ToDictionary();
```

2024-04-23 05:22 UTC, miyaji255 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +    private static string CreatePrompt1(string lineNumberingText)
名前をもう少しわかりやすくして欲しい

2024-04-23 05:29 UTC, miyaji255 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +                characterListEndIndex = i;
```suggestion
                characterListEndIndex = i;
                break;
```

2024-04-23 05:38 UTC, miyaji255 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +            {{sb2}}
string.Joinを使ってもいいかも
```suggestion
        return $$"""
            Assign the most fitting voice type to each character from the provided list, ensuring the chosen voice aligns with their role and attributes in the story. Only select from the available voice types.

            Characters:
            {{characterList.Aggregate(new StringBuilder(),
                (builder, character) => builder.AppendLine($"c{character.Id}. {character.Name}: {character.Description}"))}}

            Voice Types:
            {{_soundGenerationSelectorService.Models.Aggregate(new StringBuilder(),
                (builder, voiceType) => builder.AppendLine($"{voiceType.Name},"))}}
```

2024-04-23 05:47 UTC, miyaji255 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +        }
`List`は使わずにかけそう。
```cs
        var characters = lines.Skip(characterListStartIndex + 1)
            .Take(characterListEndIndex - characterListStartIndex + 1)
            .Where(l => l.StartsWith('c'))
            .Select(l =>
            {
                var dotIndex = l.IndexOf('.');
                var colonIndex = l.IndexOf(':');
                return new Character(l[1..dotIndex], l[(dotIndex + 2)..colonIndex], l[(colonIndex + 2)..]);
            }).ToArray();
```

2024-04-28 08:07 UTC, miyaji255 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +        var dic = characterList.Select(x => KeyValuePair.Create(x.Id, x.Name)).ToDictionary();
変数名をわかりやすくしてほしいです。
KeyValuePairではなくValueTuple<T1,T2>でもToDisctionaryできます

2024-04-28 08:11 UTC, miyaji255 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +            line = line[..line.IndexOf(' ')];
前のほうがわかりやすかったと思いますが変更した理由は何ですか？また、`lines2`をもう少しわかりやすい変数名にしてほしいです。

2024-04-28 08:13 UTC, miyaji255 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +        var characterListEndIndex = 0;
正直SkipWhile+TakeWhileでいいと思います。もちろんこちらのほうがパフォーマンスが出るかもしれませんがさほど変わらないと思われるので、読みやすさを取るほうがいいと思います。 @herring101 と検討してください

2024-04-28 18:14 UTC, aiueo-1234 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +            line = line[..line.IndexOf(' ')];
同時発話の時に二人以上のキャラを出すので、暫定対応で先頭のキャラのみにするためです。
本格的にやるには、ScriptLineのキャラを配列にしたり、StyleBertVitsの合成音声を重ねたりするなどの処理が必要なのでやるなら別issueでやるべきだと思いました。

2024-04-29 01:02 UTC, miyaji255 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +            line = line[..line.IndexOf(' ')];
それならSplitの引数を確認しないだけで良かったと思います。

2024-04-29 01:04 UTC, miyaji255 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +        var dic = characterList.Select(x => KeyValuePair.Create(x.Id, x.Name)).ToDictionary();
characterIdNameDictionaryは型名と被っており、冗長だと思います。`characterId2Name`ぐらいでいいと思います。

2024-04-29 01:06 UTC, miyaji255 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +               }
IndexOfAnyは`,`or` `という意味ですが意図通りですか？また、どうせstring化するなら一度Span西なくても良いと思います。

2024-04-29 01:16 UTC, miyaji255 requested changes

2024-04-29 01:16 UTC, miyaji255 commented on KoeBook.Core/Services/ClaudeService.cs
> +        return _anthropic;
以下のバグがあります。`_apiKey`と`_anthropic`の両方にnullを入れるのがいいと思います。

1. ApiKeyによってAntropicが作成される
2. ApiKeyがnullになる
3. GetAnthropicを呼ぶ => nullが返る
4. GetAnthropicを呼ぶ => 1で作成されたAnthropicが返る

2024-04-29 04:34 UTC, miyaji255 commented on KoeBook.Core/Services/StyleBertVitsClientService.cs
> +            var requestUri = new Uri(baseUri, path);
uriを経由するようにした理由は何ですか？

2024-04-29 05:41 UTC, aiueo-1234 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +               }
意図通りの動作です。またspanにしたのはSearchValuesを使って見たかったからです。

2024-04-29 05:45 UTC, aiueo-1234 commented on KoeBook.Core/Services/StyleBertVitsClientService.cs
> +            var requestUri = new Uri(baseUri, path);
単純にhttpclientを使われているのと、元の結合方法だとroot//pathになったのでどっちに/をいれるのかを考えたくないからです

2024-04-29 06:11 UTC, miyaji255 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +               }
了解しました。

> `l[(l.IndexOf(':') + 2)..]`

ここで一度string化を挟んでいるのでこれを取り除いてください。また、IndexOfAnyをキャッシュして評価回数を一度にしてください。

2024-04-29 06:13 UTC, miyaji255 commented on KoeBook.Core/Services/StyleBertVitsClientService.cs
> +            var requestUri = new Uri(baseUri, path);
外部に公開しているわけでもないので`/`あるなしの両方を許容する必要はないと思います。

2024-04-29 06:24 UTC, aiueo-1234 commented on KoeBook.Core/Services/StyleBertVitsClientService.cs
> +            var requestUri = new Uri(baseUri, path);
uriを経由したほうが安全だと思うのでこのほうが良いと思います。

2024-04-29 06:37 UTC, miyaji255 commented on KoeBook.Core/Services/StyleBertVitsClientService.cs
> +            var requestUri = new Uri(baseUri, path);
実行したらデバッグ時に自明にわかるバグなので別にそこまでする必要はないと思います。

2024-04-29 06:44 UTC, miyaji255 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +            (var characterList, var characterIdNameDictionary) = ExtractCharacterList(message1.ToString(), scriptLines);
```suggestion
            var (characterList, characterIdNameDictionary) = ExtractCharacterList(message1.ToString(), scriptLines);
```

2024-04-29 07:32 UTC, aiueo-1234 commented on KoeBook.Core/Services/StyleBertVitsClientService.cs
> +            var requestUri = new Uri(baseUri, path);
いま思い出しましたが、一度間違えてrootを入れた後にアプリを終了させると、mockに切り替えない限りアプリが軌道できなくなる（StyleBertVtisにアクセスできない->エラー->アプリ終了）のでダメです。

2024-04-29 07:37 UTC, miyaji255 commented on KoeBook.Core/Services/StyleBertVitsClientService.cs
> +            var requestUri = new Uri(baseUri, path);
それはすみません。こちらの実装の問題ですので #40 で修正します

2024-04-29 09:06 UTC, miyaji255 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +        }
Zip+foreachを使えばToArrayする必要はないと思います

2024-04-29 09:06 UTC, miyaji255 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +            }).ToList();
長さが変わらないので配列でも良いのではないでしょうか？

2024-04-29 09:28 UTC, miyaji255 commented on KoeBook.Core/Services/ClaudeAnalyzerService.cs
> +        if (voiceIdLines.Count() != scriptLines.Count)
ここでCountすると2度イテレートすることになってしまいます。
少し邪道ですがZip=>Select (foreachの替わり) => Count とすれば一度で済みます

2024-04-29 10:57 UTC, miyaji255 commented on KoeBook.Core/Contracts/Services/ILlmAnalyzerService.cs
> +    ValueTask<BookScripts> LlmAnalyzeScriptLinesAsync(BookProperties bookProperties, List<ScriptLine> scriptLines, CancellationToken cancellationToken);
ここの`List<ScriptLine>`も配列に変えられませんか？

2024-04-29 11:37 UTC, aiueo-1234 commented on KoeBook.Core/Contracts/Services/ILlmAnalyzerService.cs
> +    ValueTask<BookScripts> LlmAnalyzeScriptLinesAsync(BookProperties bookProperties, List<ScriptLine> scriptLines, CancellationToken cancellationToken);
変更箇所が多くなるのでできればこのままでいきたいです。(GPT4, BookScriptsなど）

2024-04-29 11:52 UTC, miyaji255 commented on KoeBook.Core/Contracts/Services/ILlmAnalyzerService.cs
> +    ValueTask<BookScripts> LlmAnalyzeScriptLinesAsync(BookProperties bookProperties, List<ScriptLine> scriptLines, CancellationToken cancellationToken);
あまり変える機会がなさそうなのでこのタイミングで変えたいと思ったのですがどうでしょうか？

2024-04-30 11:54 UTC, miyaji255 submitted a review, later dismissed

2024-04-30 16:07 UTC, merged