#1-4 生成タスク周りをリファクタリング
OUCC/KoeBook pull request #31
Opened 2024-04-04 11:19 UTC by miyaji255

2024-04-04 15:27 UTC, aiueo-1234 requested changes

2024-04-04 15:27 UTC, aiueo-1234 commented on Epub/KoeBook.Epub/Services/AnalyzerService.cs
> +                        var rubyDict = ExtractRuby(line).ToDictionary();
ToDictionary()すると、行中で同じ漢字に対して違う読みを当てる場合にコケると思うので`IEnumerable<KeyValuePair<string, string>>`のままにするか、タプルのListや配列にしておいてください。

2024-04-04 15:27 UTC, aiueo-1234 commented on Epub/KoeBook.Epub/Services/AnalyzerService.cs
>      private Dictionary<string, string> _rubyReplacements = new Dictionary<string, string>();
ルビを保存して音声合成時に正しい読みを与える目的で保存してたと思うのですが、機能してないので消していいと思います。

2024-04-04 15:27 UTC, aiueo-1234 commented on Epub/KoeBook.Epub/Services/AnalyzerService.cs
>                          var line = paragraph.Text;
ここでは`null`でないはずなので、ずっと出てる警告を消すためにも`?? ""`か`?? throw new Exception()`でいいと思います

2024-04-04 15:27 UTC, aiueo-1234 commented on Epub/KoeBook.Epub/Services/AnalyzerService.cs
>      private static string ReplaceBaseTextWithRuby(string text, Dictionary<string, string> rubyDict)
rubyDictの型を別の個所で指摘したように変更しておいてください。

2024-04-04 15:27 UTC, aiueo-1234 commented on Epub/KoeBook.Epub/Services/AnalyzerService.cs
> +    [GeneratedRegex("<ruby><rb>(.*?)</rb><rp>（</rp><rt>(.*?)</rt><rp>）</rp></ruby>")]
フリガナのカッコは
- 全角かっこ
- 半角スペース＋半角かっこ
- 上記二つの混合

のいずれかが考えられると思うので修正できたらしてほしいです。

2024-04-04 23:18 UTC, miyaji255 commented on Epub/KoeBook.Epub/Services/AnalyzerService.cs
>      private Dictionary<string, string> _rubyReplacements = new Dictionary<string, string>();
ではそもそもExtractRubyがいりませんね？

2024-04-04 23:25 UTC, miyaji255 commented on Epub/KoeBook.Epub/Services/AnalyzerService.cs
>      private Dictionary<string, string> _rubyReplacements = new Dictionary<string, string>();
Rubyタグのついていないルビは置換できませんが良いですね？

2024-04-05 05:16 UTC, aiueo-1234 requested changes

2024-04-05 05:16 UTC, aiueo-1234 commented on Epub/KoeBook.Epub/Services/AnalyzerService.cs
>      private Dictionary<string, string> _rubyReplacements = new Dictionary<string, string>();
やるならその対応は別issueでやりましょう。なのでいったん削除でいいと思います。

2024-04-05 05:16 UTC, aiueo-1234 commented on KoeBook.Test/Epub/AnalyzerServiceTest.cs
> +    public void ReplaceBaseTextWithRuby(string input, string expected)
`[InlineData("ああ<ruby><rb>漢字</rb><rp>（</rp><rt>かんじ</rt><rp>）</rp></ruby>あああ<ruby><rb>漢字</rb><rp>（</rp><rt>カンジ</rt><rp>）</rp></ruby>", "ああかんじあああカンジ")]`を追加してください

2024-04-05 06:07 UTC, miyaji255 commented on Epub/KoeBook.Epub/Services/AnalyzerService.cs
>      private Dictionary<string, string> _rubyReplacements = new Dictionary<string, string>();
okです

2024-04-05 11:52 UTC, aiueo-1234 approved these changes

2024-04-05 11:53 UTC, merged