xmlの小説の読み込み部分の作成
OUCC/KoeBook pull request #38
Opened 2024-04-28 09:07 UTC by TakenPt

2024-04-28 18:55 UTC, aiueo-1234 requested changes

2024-04-28 18:55 UTC, aiueo-1234 commented on KoeBook/Models/GenerationTask.cs
> +        _title = sourceType == SourceType.FilePath ? Path.GetFileName(source) : source;
この分岐は意味がない気がします

2024-04-28 18:55 UTC, aiueo-1234 commented on KoeBook/Models/GenerationTask.cs
>      public bool SkipEditChangable => State < GenerationState.Editting;
fix typo (Changable -> Changeable)

2024-04-28 18:55 UTC, aiueo-1234 commented on KoeBook.Core/Models/BookProperties.cs
> +        Source = aiStory;
SourceTypeの設定忘れ

2024-04-28 18:55 UTC, aiueo-1234 commented on KoeBook.Core/Models/BookProperties.cs
> +﻿using System.Diagnostics;
不要なusingの削除

2024-04-28 18:55 UTC, aiueo-1234 commented on Epub/KoeBook.Epub/Services/AiStoryAnalyzerService.cs
> +﻿using KoeBook.Core.Utilities;
不要なusingの削除

2024-04-29 01:17 UTC, miyaji255 commented on KoeBook/Models/GenerationTask.cs
> +        _title = sourceType == SourceType.FilePath ? Path.GetFileName(source) : source;
いつでもFilePathに対応できるように残しています

2024-04-29 05:53 UTC, aiueo-1234 commented on KoeBook/Models/GenerationTask.cs
> +        _title = sourceType == SourceType.FilePath ? Path.GetFileName(source) : source;
了解です

2024-04-29 05:56 UTC, aiueo-1234 approved these changes
LGTM

2024-04-29 06:07 UTC, merged