簡単な表紙画像の生成
OUCC/KoeBook pull request #39
Opened 2024-04-29 04:09 UTC by TakenPt

2024-04-29 04:36 UTC, miyaji255 requested changes

2024-04-29 04:36 UTC, miyaji255 commented on KoeBook/Services/CreateCoverFileService.cs
> +            using Font authorFont = new Font("游ゴシック Medium", 75, FontStyle.Bold);
using varでいけると思います

2024-04-29 04:36 UTC, miyaji255 commented on KoeBook/Services/CreateCoverFileService.cs
> +            using Bitmap bitmap = new Bitmap(1800, 2560);
この大きさにした理由をコメントに残しておいてください。

2024-04-29 04:36 UTC, miyaji255 commented on KoeBook/Services/CreateCoverFileService.cs
> +        }
Tryにする意味があまり感じられないので例外を投げればよいと思います。

2024-04-29 13:15 UTC, miyaji255 commented on KoeBook/Services/CreateCoverFileService.cs
> +            using Brush brush = new SolidBrush(Color.Black);
`Brushes.Black`は使えないですか？

2024-04-29 23:06 UTC, miyaji255 commented on KoeBook/Services/CreateCoverFileService.cs
> +            stringFormat.LineAlignment = StringAlignment.Center;
```suggestion
            using var stringFormat = new StringFormat()
            {
                Alignment = StringAlignment.Center,
                LineAlignment = StringAlignment.Center,
            };
```

2024-04-29 23:06 UTC, miyaji255 commented on KoeBook/Services/CreateCoverFileService.cs
> +            return;
ここのreturnはいらないです。

2024-04-29 23:07 UTC, miyaji255 commented on KoeBook/Services/CreateCoverFileService.cs
> +            throw new EbookException(ExceptionType.CreateCoverFileFailed, ex.Message);
innerExceptionにexを指定してください

2024-04-30 00:49 UTC, TakenPt commented on KoeBook/Services/CreateCoverFileService.cs
> +            throw new EbookException(ExceptionType.CreateCoverFileFailed, ex.Message);
` EbookException(ExceptionType.CreateCoverFileFailed, ex.Message, ex);`
これで合ってますか？

2024-04-30 02:19 UTC, miyaji255 commented on KoeBook/Services/CreateCoverFileService.cs
> +            throw new EbookException(ExceptionType.CreateCoverFileFailed, ex.Message);
それで大丈夫です

2024-04-30 05:08 UTC, miyaji255 commented on KoeBook/Services/CreateCoverFileService.cs
> +            using var brush = Brushes.Black;
自分の管理外のオブジェクトをusingするのは良くないです

2024-04-30 09:49 UTC, miyaji255 approved these changes
LGTM

2024-05-01 02:10 UTC, merged